config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts,:pictures, :profiles do
  	resources :posts,:pages
  end
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'profiles/:profile_id/tags/:tag', to: 'posts#index'
  get 'profiles/:profile_id/categories/:cate_id', to: 'posts#index'
  get 'profiles/:search_keyword', to: 'profiles#index'
  #root "posts#index"
  root to: "posts#index"

  if Rails.env.production?
    mount Shrine.presign_endpoint(:cache) => "/presign"
  else
    # In development and test environment we're using filesystem storage
    # for speed, so on the client side we'll upload files to our app.
    mount Shrine.upload_endpoint(:cache) => "/upload"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  #belongs_to :post
  include ImageUploader::Attachment.new(:image) 
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :categorys
	has_many :pictures, dependent: :destroy
  	accepts_nested_attributes_for :pictures, allow_destroy: true

	#serialize เกี่ยวกับการตัดอัขระ ก่อนเก็บลง ดาต้าเบส  อันนี้ยังติดไว้อยู่ ยังไม่เข้าใจ
	#serialize :categories
	
	include ImageUploader::Attachment.new(:cover_photo)

	validates :title, presence: true
	validates :categories, presence: true
	validates_presence_of :cover_photo

	#has_attached_file :image, styles: { large: "1000x1000>", medium: "480x480>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	#validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	#tag list
  	acts_as_taggable

  	


end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  #validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  include ImageUploader::Attachment.new(:avatar)

  def self.search(search)
    if search
      where('firstname LIKE ?', "%#{search}%")
    else
      all
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index,:show]
	layout :resolve_layout

	def index
		@categories = Category.all
		if params[:profile_id]
			@user = User.find(params[:profile_id])
			if params[:tag]
				@post = @user.posts.tagged_with(params[:tag]).order("created_at DESC")
			elsif params[:cate_id]
				@post = []
				@temp_post = @user.posts.order("created_at DESC")
				@temp_post.each do |temp_post|
					if temp_post.categories.include?(params[:cate_id])
						@post << temp_post
					end 
				end
			else
				@post = @user.posts.order("created_at DESC")
			end
		else
			if params[:tag]
				@post = Post.tagged_with(params[:tag]).order("created_at DESC")
			else
				@post = Post.all.order("created_at DESC")
			end
		end


	end

	def new
		@categories = Category.all
		@post = current_user.posts.build
	end

	def create
		@categories = Category.all
		@post = current_user.posts.build(post_params)

		#@post = Post.new(post_params)

		if @post.save

	      	redirect_to @post

		else
			render action: "new"
    	end
		
	end

	def show
		@categories = Category.all
		#@pictures = Picture.find(params[:post_id])
		if params[:profile_id]
			@user = User.find(params[:profile_id])
			@post = @user.posts.find(params[:id])
		else
			@post = Post.find(params[:id])
		end

	end

	def edit
		@categories = Category.all
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if current_user.id == @post.user_id
			if @post.update(post_params)
				redirect_to @post
			else
				render action: "edit"
			end
		else
			redirect_to root_path
		end
	end

	def destroy
		@post = Post.find(params[:id])

		if current_user.id == @post.user_id
			@post.destroy

			redirect_to root_path
		end
	end

	private

		def post_params
			#params.require(:post).permit(:title,:body,:cover_photo,:tag_list,categories:[])
			params.require(:post).permit!
		end

		def resolve_layout
			case action_name
			when "index","show"
				if params[:profile_id]
			  		"profile"
			  	else
			  		"application"
			  	end
			else
			  "application"
			end
		end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!, except: [:index,:show]
	layout :resolve_layout

	def show
		@user = User.find(params[:id])
		@post = @user.posts.order("created_at DESC")
	end

	def index
		@profile = User.search(params[:search]).order('firstname DESC').paginate(:per_page => 5, :page => params[:page])
	end

	private

	def profile_params
		params.require(:formsearch).permit(:search_keyword)
	end

	def resolve_layout
		case action_name
		when "show"
		  "profile"
		else
		  "application"
		end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
private

  def sign_up_params
    params.require(:user).permit(:avatar,:firstname, :surname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:avatar,:firstname, :surname, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def upload_server
    if Rails.env.production?
      :s3
    else
      :app
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <meta name="description" content="Website Profile">
   <meta name="keywords" content="website,profile">
   <title>MyInfo : Website รวม Profile บุคลากร</title>
   <!-- =============== VENDOR STYLES ===============--> 
   <!-- =============== VIEW VENDOR STYLES ===============--> 
   <!-- =============== APP STYLES ===============-->
   

   <script src="https://unpkg.com/babel-polyfill@6.26.0/dist/polyfill.min.js"></script>
    <script src="https://unpkg.com/whatwg-fetch@2.0.3/fetch.js"></script>
    <script src="https://unpkg.com/uppy@0.24.4/dist/uppy.min.js"></script>

    <link href="https://unpkjg.com/bootstrap@3.3.7/dist/css/bootstrap.min.css" media="screen" rel="stylesheet" />
    <link href="https://unpkg.com/uppy@0.24.4/dist/uppy.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= stylesheet_link_tag 'application', media: 'all', id: "maincss" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" media="all" href="<%= asset_path('themes/theme-e.css') %>" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <link rel="stylesheet" media="all" href="<%= asset_path('social-share-button.css') %>" />
    

    <script type="text/template" id="template-picture">
      <%= render partial: "posts/picture", locals: { picture: Picture.new, idx: "{{index}}" } %>
    </script>


   <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script> 


  

</head>

<body>
   
      <!-- top navbar-->
      <header class="topnavbar-wrapper">
         <%= render partial: "layouts/partials/topnavbar" %>
      </header>

      <div class="layout-boxed">
         <div class="wrapper">
         <!-- sidebar-->
            <aside class="aside">
               <%= render partial: "layouts/partials/sidebar" %>
            </aside>
           <!-- offsidebar-->
            <aside class="offsidebar hide"> 
            </aside>
            <!-- Main section-->
            <section>
               <!-- Page content-->
               <div class="content-wrapper">
                  <%= yield %>
               </div>
            </section>
            <!-- Page footer-->
            <footer>
               <%= render partial: "layouts/partials/footer" %>
            </footer>
         </div>
      </div>



   
   <!-- =============== VENDOR SCRIPTS ===============--> 
   <!-- =============== VIEW VENDOR SCRIPTS ===============--> 
   <!-- =============== APP SCRIPTS ===============-->
   <%= javascript_include_tag 'application' %>



   <%= yield :body_area %> 

</body>

</html>

app/views/layouts/partials/_footer.html.erb
<small><span>&copy; 2018 - พัฒนาระบบโดย <a href="http://www.biza.me" target="_blank">Biza Enterprise Co.,ltd.</a></span></small>

app/views/layouts/partials/_sidebar.html.erb
<!-- START Sidebar (left)-->
<div class="aside-inner">
   <nav class="sidebar" data-sidebar-anyclick-close="">
      <!-- START sidebar nav-->
      <ul class="nav">
       <!-- START user info-->

        <li class="mb-xl">
          <div class="panel-body mt-xl">
           <div class="">
              <div class="text-center">
                 <img src="<%= image_path('logo_tru_400.png') %>" alt="มหาวิทยาลัยราชภัฏเทพสตรี" class="img-thumbnail img-circle thumb128">
              </div>
           </div>
           <div class="text-center">
              <h3 class="text-white">มหาวิทยาลัยราชภัฏ<br>เทพสตรี </h3>
              <p class="text-muted">อําเภอเมืองลพบุรี ลพบุรี</p>
           </div>

          </div>  
        </li>

        <li class="<%= 'active' if controller_name == ('profiles') %> bb mt">
          <%= link_to(raw("<em class='icon-notebook'></em><span>รวมโปรไฟล์</span>") , profiles_path) %>
        </li>
        <li class="<%= 'active' if controller_name == ('posts') %> bb mt">
          <%= link_to(raw("<em class='icon-grid'></em><span>รวมโพส</span>") , posts_path) %>
        </li>

        
         
      </ul>
      <!-- END sidebar nav-->
   </nav>
</div>
<!-- END Sidebar (left)-->

app/views/layouts/partials/_sidebar_profile.html.erb
<% #profile_find(params[:id]) %>
<!-- START Sidebar (left)-->
<div class="aside-inner">
   <nav class="sidebar" data-sidebar-anyclick-close="">
      <!-- START sidebar nav-->
      <ul class="nav">
       <!-- Iterates over all sidebar items-->
        <li class="<%= 'active' if controller_name == ('profiles') %> bb mt">
          <%= link_to(raw("<em class='icon-notebook'></em><span>รวมโปรไฟล์</span>") , profiles_path) %>
        </li>
        <li class="<%= 'active' if controller_name == ('posts') %> bb mt">
          <%= link_to(raw("<em class='icon-grid'></em><span>รวมโพส</span>") , posts_path) %>
        </li>

        <li class="bb mb-xl">
          <div class="panel-body">
           <div class="">
              <div class="text-center">
                <% if @user.avatar_data %>
                  <%= image_tag(@user.avatar_url(:thumbnail), class: "img-thumbnail img-circle thumb128") %>
                  <% end %>
              </div>
           </div>
           <div class="text-center mt-xl">
          
              <h4 class="m0 text-white"><%= @user.firstname %> <%= @user.surname %></h4>
              <p class="text-muted">อาจารย์ประจำวิชา</p>
           </div>
           <!--
           <div class="panel-body text-center text-muted">
              <div class="row row-table">
                 <div class="col-xs-4 br">
                    <h4 class="m0 text-white">400</h4>
                    <p class="m0">กิจกรรม</p>
                 </div>
                 <div class="col-xs-4 br">
                    <h4 class="m0 text-white">2000</h4>
                    <p class="m0">บทความ</p>
                 </div>
                 <div class="col-xs-4">
                    <h4 class="m0 text-white">500</h4>
                    <p class="m0">เอกสาร</p>
                 </div>
              </div>
           </div>
-->

          </div>  
        </li>

        <li class="<%= 'active' if controller_name == ('profiles') %>">
            <% if params[:profile_id] %>
              <% profile_id = params[:profile_id] %>
            <% else %>
              <% profile_id = params[:id] %>
            <% end %>
            <%= link_to (profile_path(profile_id)), title: "หน้าแรก" do %>
                <em class="icon-speedometer"></em>
                <span>หน้าแรก</span>
            <% end %>
        </li>
        <li class="<%= 'active' if controller_name == ('pages') %>">
            <a href="" title="dashboard_operation">
                <em class="icon-question"></em>
                <span>เกี่ยวกับเรา</span>
            </a>
        </li>
        <li class="<%= 'active' if params[:cate_id] == 1 %>">
            <%= link_to ("#{profile_path(profile_id)}/categories/1") do %>
              <em class="icon-graph"></em>
              <span>กิจกรรม</span>
            <% end %>
        </li> 
        <li class="<%= 'active' if params[:cate_id] == 2 %>">
            <%= link_to ("#{profile_path(profile_id)}/categories/2") do %>
              <em class="icon-graph"></em>
              <span>บทความ</span>
            <% end %>
        </li> 
        <li class="<%= 'active' if params[:cate_id] == 3 %>">
            <%= link_to ("#{profile_path(profile_id)}/categories/3") do %>
              <em class="icon-graph"></em>
              <span>เอกสาร</span>
            <% end %>
        </li> 
         
      </ul>
      <div class="text-center mt-xl">
        <!--
        <p><button type="button" class="btn btn-labeled btn-info">
          <span class="btn-label"><i class="fa fa-share"></i>
         </span>แชร์โปรไฟล์นี้</button></p>
-->     <p class="text-white">แชร์โปรไฟล์นี้</p>
         <%= social_share_button_tag(@user.firstname, :image => @user.avatar_url(:thumbnail), desc: "มหาวิทยาลัยราชภัฏเทพสตรี") %>
      </div>
      <!-- END sidebar nav-->
   </nav>
</div>
<!-- END Sidebar (left)-->

app/views/layouts/partials/_topnavbar.html.erb
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
   <!-- START navbar header-->
   <div class="navbar-header">
      <%= link_to (posts_path) , class: "navbar-brand" do %>
         <div class="brand-logo">
            <img src="<%= image_path('logo_tru_50.png') %>" alt="App Logo" class="img-responsive" />
         </div>
         <div class="brand-logo-collapsed">
            <img src="<%= image_path('logo_tru_72.png') %>" alt="App Logo" class="img-responsive" />
         </div>
      <% end %>
   </div>
   <!-- END navbar header-->
   <!-- START Nav wrapper-->
   <div class="nav-wrapper">
      <!-- START Left navbar-->
      <ul class="nav navbar-nav col-sm-4">
         <!-- Search icon-->
         <li>


         <%= form_tag profiles_path, :method => 'get', :id => "profiles_search" , :class => "form-horizontal mt ml" do %>
            <div class="input-group">
              <%= hidden_field_tag :direction, params[:direction] %>
              <%= hidden_field_tag :sort, params[:sort] %>
                <%= text_field_tag :search, params[:search] , :placeholder => "ใส่ชื่อโปรไฟล์ที่ต้องการค้นหา" , :class => "form-control" %>
                     <span class="input-group-btn">
                        <button type="submit" class="btn btn-default">
                           <em class="fa fa-search"></em>
                        </button>
                     </span>
            </div>
         <% end %>

         </li>
         <!-- END lock screen-->
      </ul>
      
      <!-- END Left navbar-->
      <!-- START Right Navbar-->
      <ul class="nav navbar-nav navbar-right">

         <% if !user_signed_in? %>
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <%= link_to (new_user_session_path) ,id: "user-block-toggle" do %>
               <em class="icon-login"></em> เข้าสู่ระบบ
            <% end %>
         </li>
         <% else %>
         <li>
            <%= link_to (new_post_path) ,class: "button" do %>
               <em class="icon-plus"></em> เพิ่มข้อมูล
            <% end %>
         </li>
         <li>
            <%= link_to (edit_user_registration_path) ,class: "button" do %>
               <em class="icon-note"></em> <span class="hidden-sm">แก้ไขข้อมูลส่วนตัว</span>
            <% end %>
         </li>
         <li>
            <%= link_to (profile_path(current_user.id)), class: "pt-sm pb-sm" do %>
            <div class="user-block-picture">
               <div class="user-block-status">
                  <% if current_user.avatar_data %>
                     <%= image_tag(current_user.avatar_url(:thumbnail), class: "img-thumbnail img-circle" ,width: "40", height: "40") %>
                  <% end %>
                  <span>
                     <%= link_to (profile_path(current_user.id)) do %>
                        <%= current_user.firstname %> <%= current_user.surname %>
                        <% end %>     
                  </span>
               </div>
            </div>
            <% end %>
         </li>
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <%= link_to (destroy_user_session_path) , method: :delete do %>
               <em class="icon-logout"></em> <span class="hidden-md hidden-sm">ออกจากระบบ</span>
            <% end %>
         </li>
         <% end %>
      </ul>
      <!-- END Right Navbar-->
   </div>
   <!-- END Nav wrapper-->
</nav>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <meta name="description" content="Bootstrap Admin App + Ruby on Rails">
   <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
   <title>MyInfo : Website รวม Profile บุคลากร</title>
   <!-- =============== VENDOR STYLES ===============--> 
   <!-- =============== VIEW VENDOR STYLES ===============--> 
   <!-- =============== APP STYLES ===============-->
   <%= stylesheet_link_tag 'application', media: 'all', id: "maincss" %>
   <%= csrf_meta_tags %>
   <link rel="stylesheet" media="all" href="<%= asset_path('themes/theme-e.css') %>" />
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
   <link rel="stylesheet" media="all" href="<%= asset_path('social-share-button.css') %>" />

   <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script> 

 
</head>

<body>
      <!-- top navbar-->
      <header class="topnavbar-wrapper">
         <%= render partial: "layouts/partials/topnavbar" %>
      </header>

      <div class="layout-boxed">
         <div class="wrapper">
            <!-- sidebar-->
            <aside class="aside">
               <%= render partial: "layouts/partials/sidebar_profile" %>
            </aside>
           <!-- offsidebar-->
            <aside class="offsidebar hide"> 
            </aside>
            <!-- Main section-->
            <section>
               <!-- Page content-->
               <div class="content-wrapper">
                  <%= yield %>
               </div>
            </section>
            <!-- Page footer-->
            <footer>
               <%= render partial: "layouts/partials/footer" %>
            </footer>
         </div>
   </div>
   <!-- =============== VENDOR SCRIPTS ===============--> 
   <!-- =============== VIEW VENDOR SCRIPTS ===============--> 
   <!-- =============== APP SCRIPTS ===============-->
   <%= javascript_include_tag 'application' %>

   <%= yield :body_area %> 

</body>

</html>

app/views/pages/index.html.erb
<div id="page_wrapper">
	<h1>About Us</h1>
	<p>เนื้อหา</p>
</div>

app/views/posts/edit.html.erb
<h3>แก้ไข</h3>
<div class="row">
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h3>
<% if params[:cate_id] %>
   หมวดหมู่: 
    <% category = @categories.find(params[:cate_id]) %>
    <%= category.title %>

<% elsif params[:tag]  %>
    Tag : <%= params[:tag] %>
<% else %>
  โพสทั้งหมด
<% end %>
</h3>
<div class="row">
	<% @post.each do |post|  %>
		<div class="col-md-6">
            <div class="panel">
              <% if post.cover_photo_url %>
                  <% if params[:id] %>
					       <%= link_to (image_tag post.cover_photo_url(:thumbnail) , class: "img-responsive"), "#{profile_path}/posts/#{post.id}" , class: "posts-img" %>
                 <% elsif params[:profile_id] %>
                      <%= link_to (image_tag post.cover_photo_url(:thumbnail) , class: "img-responsive"), "#{profile_path(params[:profile_id])}/posts/#{post.id}" , class: "posts-img" %>
				     <% else %>
					       <%= link_to (image_tag post.cover_photo_url(:thumbnail) , class: "img-responsive"), "/posts/#{post.id}", class: "posts-img" %>
				     <% end %>
				<% end %>
               <div class="panel-body">
                  <p class="clearfix">
                     <span class="pull-left">
                        <small class="mr-sm">
                        	โดย 
                        	<%= link_to (profile_path(post.user.id)) do %>
                        		<%= post.user.firstname %> <%= post.user.surname %>
                        	<% end %>
                        </small>
                        <small class="mr-sm">โพสเมื่อ : <%= time_ago_in_words(post.created_at) %> ที่แล้ว</small>
                     </span>

                     <!--
                     <span class="pull-right">
                        <small>
                           <strong>56</strong>
                           <span>Comments</span>
                        </small>
                     </span>
                 -->
                  </p>
                  <h4>

					<% if params[:id] %>
						<%= link_to post.title, "#{profile_path}/posts/#{post.id}" %>
					<% elsif params[:profile_id] %>
                  <%= link_to post.title, "#{profile_path(params[:profile_id])}/posts/#{post.id}", class: "img-responsive" %>
               <% else %>
						<%= link_to post.title, "/posts/#{post.id}" %>
					<% end %>
                  	
                  </h4>
                  <p><%= truncate(post.body, length:100) %></p>
               </div>
            </div>
         </div>


	<% end %>
</div>

app/views/posts/new.html.erb
<h3>สร้างโพส</h3>
<div class="row">
	<%= render 'form' %>
	
</div>

app/views/posts/show.html.erb
<div class="row">
		<!-- Blog Content-->
		<div class="col-lg-12">
         <div class="panel panel-default">
            <div class="panel-heading">
               <div class="bb">
                  <h2 class=" mb-xl"><%= @post.title %></h2>
                  <p class="clearfix">
                     <span class="pull-left">
                        <small>
                           <% if @post.categories && params[:profile_id] %>
                           หมวดหมู่: 
                           <% @categories.each do |category| %>
                              <% if @post.categories.include?(category.id.to_s) %>
                                 <%= link_to category.title , "#{profile_path(params[:profile_id])}/categories/#{category.id}" , class: "btn btn-xs btn-green btn-outline" %>
                                 </label>
                              <% end %> 
                           <% end %>
                           <% end %>  
                        </small>
                     </span>
                     <span class="pull-right">
                        <small class="mr-sm">
                           โดย 
                           <%= link_to (profile_path(@post.user.id)) do %>
                              <%= @post.user.firstname %> <%= @post.user.surname %>
                           <% end %>
                        </small>
                        <small class="mr-sm">
   		โพสเมื่อ : <%= time_ago_in_words(@post.created_at) %> ที่แล้ว</small>
   					<!--
                        <small>
                           <strong>56</strong>
                           <span>Comments</span>
                        </small>
                    -->
                     </span>
                  </p>
                  <p>
                  	<% if user_signed_in? && (current_user.id == @post.user_id) %>
   					<%= link_to 'แก้ไข' , edit_post_path(@post), class: "btn btn-info" %>
   					<%= link_to 'ลบ' , post_path(@post), method: :delete, data: { confirm: 'ต้องการลบ'}, class: "btn btn-danger" %>
   				<% end %>
                  </p>
               </div>
            </div>
            <div class="panel-body">
            	<% if @post.cover_photo_url %>
   			      <%= image_tag @post.cover_photo_url(:thumbnail) , class: "" %>
   			   <% end %>
            </div>
            <div class="panel-body">
            	
               <%= @post.body %>
               <ul class="list-unstyled file-upload-list" id="post-picture-list">
                  <% @post.pictures.each_with_index do |picture, idx| %>
                     <%= image_tag picture.image_url(:thumbnail) , width: 300 , class: "" %>
                  <% end %>
               </ul>
               <hr>
               <p><small>Tags: 
                     <% @post.tag_list.each do |tag| %>

                        <% if params[:profile_id] %>
                           <%= link_to tag, "#{profile_path(params[:profile_id])}/tags/#{tag}", class: "mb-sm btn btn-primary btn-outline btn-xs" %>
                        <% else %>
                           <%= link_to tag, tag_path(tag), class: "mb-sm btn btn-primary btn-outline btn-xs" %>
                        <% end %>
                     <% end %></small>
               </p> 
               <hr>
               <div class="social_share_button_content">
               <%= social_share_button_tag(@post.title,  :image => @post.cover_photo_url, desc: @post.body) %>
               </div>
            </div>
         </div> 
		</div> 
</div>

app/views/profiles/index.html.erb
<h3>รวมโปรไฟล์</h3>
<div class="row">

	<% @profile.each do |profile|  %>
	<div class="col-md-3">
      <div class="panel panel-default">
         <div class="panel-heading">
            <a href="#" class="pull-right text-muted">
               <em class="fa"></em>
            </a>
         </div>
         <div class="panel-body text-center">
            
            <%= link_to (profile_path(profile.id)) do %>
               <% if profile.avatar_data %>
                  <%= image_tag(profile.avatar_url(:thumbnail), class: "center-block img-responsive img-circle thumb96") %>
               <% end %>
            <% end %>


            <h4>
               <%= link_to (profile_path(profile.id)) do %>
                  <%= profile.firstname %> <%= profile.surname %>
               <% end %>
            </h4>
            <p>สมัครสมาชิกเมื่อ : <%= time_ago_in_words(profile.created_at) %></p>
         </div>
         <div class="panel-footer clearfix">
            <div class="pull-left">
               <%= link_to "ดูโปรไฟล์", profile_path(profile.id), class: "btn btn-xs btn-primary" %>
            </div>
            <div class="pull-right">
            	<%= link_to "แชร์", profile_path(profile.id) %>
            </div>
         </div>
      </div>
   </div>

	<% end %>
   <%= will_paginate @profile %>

</div>

app/views/profiles/show.html.erb
<%= render template: "posts/index" %>